name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:  # Allows you to manually run this workflow

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories, activity, languages, achievements, stars  # Metrics to include
          config_timezone: "auto"
          plugin_streak: yes  # Show streak stats
          plugin_stars: yes  # Show stars received
          plugin_languages: yes  # Show top languages
          plugin_repositories: yes  # Show repositories
          plugin_achievements: yes  # Show achievements
          plugin_lines: yes  # Show lines of code written
          config_display: large  # Larger display size
